# Generated by Django 5.1.2 on 2024-12-19 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userleagueplacement',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='userleagueplacement',
            index=models.Index(fields=['league_group', 'exp_earned'], name='leaderboard_league__757ded_idx'),
        ),
        migrations.AddIndex(
            model_name='userleagueplacement',
            index=models.Index(fields=['user', 'league_group'], name='leaderboard_user_id_26776c_idx'),
        ),
    ]
