# Generated by Django 5.1.2 on 2024-12-20 10:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0002_alter_userleagueplacement_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userleagueplacement',
            name='leaderboard_league__757ded_idx',
        ),
        migrations.RemoveIndex(
            model_name='userleagueplacement',
            name='leaderboard_user_id_26776c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userleagueplacement',
            unique_together={('user', 'league_group')},
        ),
    ]
